### ISSUE TITLE
Python 2.7 did not detect IPv6 addresses

### ISSUE THREAD

**Issue by mvoehringer** [DigitaleGesellschaft/Anonip#34]
`
echo "test.de 2001:0db8:85a3:0000:0000:8a2e:0370:7334 - - [21/Nov/2019:11:07:56 +0000]  - - - -" | /usr/local/sbin/anonip.py --column 2
WARNING:__main__:u'2001' does not appear to be an IPv4 or IPv6 network
test.de 2001:0db8:85a3:0000:0000:8a2e:0370:7334 - - [21/Nov/2019:11:07:56 +0000]  - - - -
`

see #33 for an possible fix

**Comment by open-dynaMIX** [comment]
Resolved by #33
