### ISSUE TITLE
Python 2.7.17 yields an error while Python 3 runs fine.

### ISSUE THREAD

**Issue by n00b42** [DigitaleGesellschaft/Anonip#35]
Im use Apache and have several Python versions installed
 "python" defaults to the "2.7.17" binary

Using anonyip in Apache2 yields:
```
Traceback (most recent call last):
  File "/pathto/anonip.py", line 422, in <module>
    main()
  File "/pathto/anonip.py", line 406, in main
    print(line, file=output_file)
TypeError: write() argument 1 must be unicode, not str
AH00106: piped log program '/pathto/anonip.py --ipv4mask 8 --ipv6mask 64 --column 2 --output /var/log/apache2/access.log' failed unexpectedly
```

According to some research, it might be to some change were in this line, python2 would expect a `str`, where python3 would expect a `utf8`.
This might be fixed by adding a conversion in that case.

In my case I just changed the shebang to python3 and now it works fine for me.

**Comment by open-dynaMIX** [comment]
Thanks a lot for reporting this @n00b42 !

I've made a quick attempt at solving it in #36 . Feel free to try if it fixes the issue.

I will take a closer look in the next days.

**Comment by n00b42** [comment]
A short test on my side worked as intended so far.

Thanks.

**Comment by open-dynaMIX** [comment]
@n00b42 Thanks for helping to fix this!
