### ISSUE TITLE
IP Adresses with Ports doesn't get masket

### ISSUE THREAD

**Issue by huggenknubbel** [DigitaleGesellschaft/Anonip#43]
i have some apache logs that looks like
> [Tue Apr 21 21:10:08.859997 2020] [php7:warn] [pid 16519] [client 89.154.188.26:57424] PHP Warning:

thats in the error.log. The combined log looks fine. but there is no port behind the IP Adress.
Some quick test with python 2 looks like:
```
192.168.2.1
--> 192.168.0.0
192.168.2.1:16852
--> 192.168.2.1:16852
```

**Comment by open-dynaMIX** [comment]
Please show us the exact command you use for processing the log.

By default Anonip splits the log by spaces and expects the ip address in the first column. For processing the line in your example, you need to provide the `-c`/`--column` argument (1-based integer):

``` shell
$ echo "[Tue Apr 21 21:10:08.859997 2020] [php7:warn] [pid 16519] [client 89.154.188.26:57424] PHP Warning:" | anonip -c 10
[Tue Apr 21 21:10:08.859997 2020] [php7:warn] [pid 16519] [client 89.154.176.0:57424] PHP Warning:
```

You can provide multiple columns for Anonip to check for an ip.

**Comment by open-dynaMIX** [comment]
@huggenknubbel I close this issue. If you still think something doesn't work right, feel free to reopen.
