### ISSUE TITLE
piped anonymization in apache not working

### ISSUE THREAD

**Issue by red-scare** [DigitaleGesellschaft/Anonip#68]
Hey,
for days now i try to get anonip.py combined with piped logs in apache2 up and running. I'm really frustrated since i've tried so many things, from changing permissions of severeal files and folders, trying every possible notation in the `access.conf` and even to re-write the anonip.py itself, but to no avial. The ip adresses in `access.log` doesn't change at all. 
Did i miss something?

### Current Behavior:
Adding a  custom log pipe to Apache with anonip.py as target doesn't change the ip adresses in `access.log`. The entries simply doesn't change.

### Expected Behavior:
Changed ip adresses in `access.log` from something like:

`192.168.137.95 - - [28/Jul/2022:15:51:14 +0200] "GET / HTTP/1.1" 200 1162 ....`

to

`192.168.[another number].[yet another number] - - [28/Jul/2022:15:51:14 +0200] "GET / HTTP/1.1" 200 1162 ...`

### Steps To Reproduce:

1. Add `CustomLog "|/var/www/anonip.py --ipv4mask 12 --output /var/log/apache2/access.log" combined` to `/etc/apache2/apache2.conf`
so the whole logging part of the config file looks like:

`LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined`
`LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined`
`CustomLog "|/var/www/anonip.py --ipv4mask 12 --output /var/log/apache2/access.log" combined`
`LogFormat "%h %l %u %t \"%r\" %>s %O" common`
`LogFormat "%{Referer}i -> %U" referer`
`LogFormat "%{User-agent}i" agent`

2. restart apache with `sudo systemctl restart apache2`
3. connect to webserver

So far there no error messages. The only `error.log` entries are: 
`[Thu Jul 28 15:54:40.131208 2022] [mpm_prefork:notice] [pid 46167] AH00169: caught SIGTERM, shutting down`
`[Thu Jul 28 15:55:11.728647 2022] [mpm_prefork:notice] [pid 46218] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations`
`[Thu Jul 28 15:55:11.728716 2022] [core:notice] [pid 46218] AH00094: Command line: '/usr/sbin/apache2'`

### Environment:
- OS: Ubuntu 20.04 x64 (VMImage running on VMWare Workstation Player)
- Apache Version: Server version: Apache/2.4.41 (Ubuntu) ;  Server built:   2022-06-14T13:30:55
- Python Version: 3.8

### Anything else:
However calling the script by hand, like: 
`/path/to/script/anonip.py --ipv4mask 12 < /var/log/apache2/access.log --output /home/user/foobar.log`
or  `/path/to/script/anonip.py --ipv4mask 12 < /var/log/apache2/access.log --output /var/log/apache2/access.log`
works just fine.

**Comment by tolimar** [comment]
Hi red-scare!

I'm happily using anonip.py on several Debian systems with Apache, and it worked with the 2.4.38 as well as 2.4.54 packages shipped there.  So I would assume it would work with the Ubuntu 2.4.41 packages as well.

And as you point out, that it works when called by hand, I assume there is a small mistake in your apache configuration.  You wrote that you changed `/etc/apache2/apache2.conf`, but as far as I know Ubuntu and Debian by default ship with site configurations overloading the main logging configuration:
```
/etc/apache2/sites-available$ grep CustomLog 000-default.conf default-ssl.conf 
000-default.conf:	CustomLog ${APACHE_LOG_DIR}/access.log combined
default-ssl.conf:		CustomLog ${APACHE_LOG_DIR}/access.log combined
```

So can you please check, if you have any additional settings for log files in possible site configurations you are using?  You'll find them in the `/etc/apache2/sites-endabled/` folder.


Best regards,
  Tolimar

**Comment by red-scare** [comment]
Hi Tolimar,

thank you very much. Indeed i only changed the `/etc/apache2/apache2.conf` . 
After adding the appropriate line into `/etc/apache2/sites-enabled/000-default.conf` it worked like a charm.

Kind regards,
red-scare
