### ISSUE TITLE
Old "homepage" shall point here

### ISSUE THREAD

**Issue by htgoebel** [DigitaleGesellschaft/Anonip#9]
The old homepage https://www.privacyfoundation.ch/de/service/anonip.html should prominently point to this repository.

The old homepage ist stll the first hit when searching the web for "apache log anonip" and It took me some time to figure out there is this repo and anonip is still maintained.

**Comment by datenreisen** [comment]
Dear Hartmut,

Thanks for your suggestion. The old webpage points now to this repository.

Thank you and all the best,
Kire

**Comment by htgoebel** [comment]
Thanks for fixing this lightning fast. I jsut discovered that only the German page was changed. The English one still lacks a pointer to here.

**Comment by datenreisen** [comment]
You're right. Just fixed as well!
